[package]
name = "application"
version.workspace = true
edition.workspace = true
authors.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
error-stack = { workspace = true }

kernel = { path = "../kernel" }
