-- SQL dump generated using DBML (dbml.dbdiagram.io)
-- Database: PostgreSQL
-- Generated at: 2024-07-04T13:28:02.884Z

CREATE TABLE "account_events" (
  "version" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "account_id" UUID NOT NULL,
  "event_name" TEXT NOT NULL,
  "data" JSON NOT NULL,
  "created_at" TIMESTAMP NOT NULL,
  PRIMARY KEY ("account_id", "version")
);

CREATE TABLE "accounts" (
  "id" UUID PRIMARY KEY,
  "name" TEXT NOT NULL,
  "private_key" TEXT NOT NULL,
  "public_key" TEXT NOT NULL,
  "is_bot" BOOLEAN NOT NULL,
  "created_at" TIMESTAMP NOT NULL,
  "deleted_at" TIMESTAMP
);

CREATE TABLE "remote_accounts" (
  "id" UUID PRIMARY KEY NOT NULL,
  "acct" TEXT UNIQUE NOT NULL,
  "url" TEXT UNIQUE NOT NULL,
  "icon_id" UUID NOT NULL
);

CREATE TABLE "profile_events" (
  "version" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "account_id" UUID NOT NULL,
  "event_name" TEXT NOT NULL,
  "data" JSON NOT NULL,
  "created_at" TIMESTAMP NOT NULL,
  PRIMARY KEY ("account_id", "version")
);

CREATE TABLE "profiles" (
  "account_id" UUID PRIMARY KEY NOT NULL,
  "display" TEXT,
  "summary" TEXT,
  "icon_id" UUID,
  "banner_id" UUID
);

CREATE TABLE "metadata_events" (
  "version" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "metadata_id" UUID NOT NULL,
  "event_name" TEXT NOT NULL,
  "data" JSON NOT NULL,
  "created_at" TIMESTAMP NOT NULL,
  PRIMARY KEY ("metadata_id", "version")
);

CREATE TABLE "metadatas" (
  "id" UUID PRIMARY KEY NOT NULL,
  "account_id" UUID NOT NULL,
  "label" TEXT NOT NULL,
  "content" TEXT NOT NULL,
  "created_at" TIMESTAMP NOT NULL
);

CREATE TABLE "stellar_hosts" (
  "id" UUID PRIMARY KEY NOT NULL,
  "url" TEXT UNIQUE NOT NULL
);

CREATE TABLE "stellar_account_events" (
  "version" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "stellar_account_id" UUID NOT NULL,
  "event_name" TEXT NOT NULL,
  "data" JSON NOT NULL,
  "created_at" TIMESTAMP NOT NULL,
  PRIMARY KEY ("stellar_account_id", "version")
);

CREATE TABLE "stellar_accounts" (
  "id" UUID PRIMARY KEY NOT NULL,
  "host_id" UUID NOT NULL,
  "client_id" TEXT NOT NULL,
  "access_token" TEXT NOT NULL,
  "refresh_token" TEXT NOT NULL
);

CREATE TABLE "stellar_emumet_accounts" (
  "emumet_id" UUID NOT NULL,
  "stellar_id" UUID NOT NULL,
  PRIMARY KEY ("emumet_id", "stellar_id")
);

CREATE TABLE "follow_events" (
  "version" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "follow_id" UUID NOT NULL,
  "event_name" TEXT NOT NULL,
  "data" JSON NOT NULL,
  "created_at" TIMESTAMP NOT NULL,
  PRIMARY KEY ("follow_id", "version")
);

CREATE TABLE "follows" (
  "id" UUID PRIMARY KEY NOT NULL,
  "follower_local_id" UUID,
  "follower_remote_id" UUID,
  "followee_local_id" UUID,
  "followee_remote_id" UUID,
  "approved_at" TIMESTAMP
);

CREATE TABLE "images" (
  "id" UUID PRIMARY KEY NOT NULL,
  "url" TEXT UNIQUE NOT NULL,
  "hash" TEXT NOT NULL,
  "blurhash" TEXT NOT NULL
);

CREATE TABLE "moderator_roles" (
  "id" UUID PRIMARY KEY NOT NULL,
  "name" TEXT NOT NULL
);

CREATE TABLE "moderator_events" (
  "version" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "stellar_id" UUID NOT NULL,
  "event_name" TEXT NOT NULL,
  "data" JSON NOT NULL,
  "created_at" TIMESTAMP NOT NULL,
  PRIMARY KEY ("stellar_id", "version")
);

CREATE TABLE "moderators" (
  "stellar_id" UUID NOT NULL,
  "role_id" UUID NOT NULL,
  PRIMARY KEY ("stellar_id", "role_id")
);

CREATE TABLE "account_report_events" (
  "version" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "report_id" UUID NOT NULL,
  "event_name" TEXT NOT NULL,
  "data" JSON NOT NULL,
  "created_at" TIMESTAMP NOT NULL,
  PRIMARY KEY ("report_id", "version")
);

CREATE TABLE "account_reports" (
  "id" UUID PRIMARY KEY NOT NULL,
  "target_id" UUID NOT NULL,
  "reported_id" UUID NOT NULL,
  "type" TEXT NOT NULL,
  "comment" TEXT NOT NULL,
  "created_at" TIMESTAMP NOT NULL,
  "closed_at" TIMESTAMP,
  "close_reason" TEXT
);

CREATE TABLE "account_moderation_events" (
  "version" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "moderation_id" UUID NOT NULL,
  "event_name" TEXT NOT NULL,
  "data" JSON NOT NULL,
  "created_at" TIMESTAMP NOT NULL,
  PRIMARY KEY ("moderation_id", "version")
);

CREATE TABLE "account_moderations" (
  "id" UUID PRIMARY KEY NOT NULL,
  "target_id" UUID NOT NULL,
  "moderator_id" UUID NOT NULL,
  "type" TEXT NOT NULL,
  "comment" TEXT NOT NULL,
  "created_at" TIMESTAMP NOT NULL,
  "closed_at" TIMESTAMP
);

CREATE TABLE "account_moderation_reports" (
  "moderation_id" UUID NOT NULL,
  "report_id" UUID NOT NULL,
  PRIMARY KEY ("moderation_id", "report_id")
);

CREATE TABLE "stellar_account_moderation_events" (
  "version" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "moderation_id" UUID NOT NULL,
  "event_name" TEXT NOT NULL,
  "data" JSON NOT NULL,
  "created_at" TIMESTAMP NOT NULL,
  PRIMARY KEY ("moderation_id", "version")
);

CREATE TABLE "stellar_account_moderations" (
  "id" UUID PRIMARY KEY NOT NULL,
  "target_id" UUID NOT NULL,
  "moderator_id" UUID NOT NULL,
  "type" TEXT NOT NULL,
  "comment" TEXT NOT NULL,
  "created_at" TIMESTAMP NOT NULL,
  "closed_at" TIMESTAMP
);

CREATE TABLE "stellar_account_moderation_reports" (
  "moderation_id" UUID NOT NULL,
  "report_id" UUID NOT NULL,
  PRIMARY KEY ("moderation_id", "report_id")
);

CREATE TABLE "host_moderation_events" (
  "version" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "moderation_id" UUID NOT NULL,
  "event_name" TEXT NOT NULL,
  "data" JSON NOT NULL,
  "created_at" TIMESTAMP NOT NULL,
  PRIMARY KEY ("moderation_id", "version")
);

CREATE TABLE "host_moderations" (
  "id" UUID PRIMARY KEY NOT NULL,
  "host_id" UUID NOT NULL,
  "moderator_id" UUID NOT NULL,
  "type" TEXT NOT NULL,
  "comment" TEXT NOT NULL,
  "created_at" TIMESTAMP NOT NULL,
  "closed_at" TIMESTAMP
);

CREATE TABLE "host_moderation_reports" (
  "moderation_id" UUID NOT NULL,
  "report_id" UUID NOT NULL,
  PRIMARY KEY ("moderation_id", "report_id")
);

ALTER TABLE "remote_accounts" ADD FOREIGN KEY ("icon_id") REFERENCES "images" ("id");

ALTER TABLE "profile_events" ADD FOREIGN KEY ("account_id") REFERENCES "accounts" ("id");

ALTER TABLE "profiles" ADD FOREIGN KEY ("account_id") REFERENCES "accounts" ("id");

ALTER TABLE "profiles" ADD FOREIGN KEY ("icon_id") REFERENCES "images" ("id");

ALTER TABLE "profiles" ADD FOREIGN KEY ("banner_id") REFERENCES "images" ("id");

ALTER TABLE "metadatas" ADD FOREIGN KEY ("account_id") REFERENCES "accounts" ("id");

ALTER TABLE "stellar_accounts" ADD FOREIGN KEY ("host_id") REFERENCES "stellar_hosts" ("id");

ALTER TABLE "stellar_emumet_accounts" ADD FOREIGN KEY ("emumet_id") REFERENCES "accounts" ("id");

ALTER TABLE "stellar_emumet_accounts" ADD FOREIGN KEY ("stellar_id") REFERENCES "stellar_accounts" ("id");

ALTER TABLE "follows" ADD FOREIGN KEY ("follower_local_id") REFERENCES "accounts" ("id");

ALTER TABLE "follows" ADD FOREIGN KEY ("follower_remote_id") REFERENCES "remote_accounts" ("id");

ALTER TABLE "follows" ADD FOREIGN KEY ("followee_local_id") REFERENCES "accounts" ("id");

ALTER TABLE "follows" ADD FOREIGN KEY ("followee_remote_id") REFERENCES "remote_accounts" ("id");

ALTER TABLE "moderator_events" ADD FOREIGN KEY ("stellar_id") REFERENCES "stellar_accounts" ("id");

ALTER TABLE "moderators" ADD FOREIGN KEY ("stellar_id") REFERENCES "stellar_accounts" ("id");

ALTER TABLE "moderators" ADD FOREIGN KEY ("role_id") REFERENCES "moderator_roles" ("id");

ALTER TABLE "account_reports" ADD FOREIGN KEY ("target_id") REFERENCES "accounts" ("id");

ALTER TABLE "account_reports" ADD FOREIGN KEY ("reported_id") REFERENCES "stellar_accounts" ("id");

ALTER TABLE "account_moderations" ADD FOREIGN KEY ("target_id") REFERENCES "accounts" ("id");

ALTER TABLE "account_moderations" ADD FOREIGN KEY ("moderator_id") REFERENCES "stellar_accounts" ("id");

ALTER TABLE "account_moderation_reports" ADD FOREIGN KEY ("moderation_id") REFERENCES "account_moderations" ("id");

ALTER TABLE "account_moderation_reports" ADD FOREIGN KEY ("report_id") REFERENCES "account_reports" ("id");

ALTER TABLE "stellar_account_moderations" ADD FOREIGN KEY ("target_id") REFERENCES "stellar_accounts" ("id");

ALTER TABLE "stellar_account_moderations" ADD FOREIGN KEY ("moderator_id") REFERENCES "stellar_accounts" ("id");

ALTER TABLE "stellar_account_moderation_reports" ADD FOREIGN KEY ("moderation_id") REFERENCES "stellar_account_moderations" ("id");

ALTER TABLE "stellar_account_moderation_reports" ADD FOREIGN KEY ("report_id") REFERENCES "account_reports" ("id");

ALTER TABLE "host_moderations" ADD FOREIGN KEY ("host_id") REFERENCES "stellar_hosts" ("id");

ALTER TABLE "host_moderations" ADD FOREIGN KEY ("moderator_id") REFERENCES "stellar_accounts" ("id");

ALTER TABLE "host_moderation_reports" ADD FOREIGN KEY ("moderation_id") REFERENCES "host_moderations" ("id");

ALTER TABLE "host_moderation_reports" ADD FOREIGN KEY ("report_id") REFERENCES "account_reports" ("id");
