[package]
name = "kernel"
version.workspace = true
edition.workspace = true
authors.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
destructure = "0.5.6"
vodca = "0.1.1"
serde = { version = "1", features = ["derive"] }
uuid = { version = "1.4", features = ["serde", "v4"] }
time = { version = "0.3", features = ["serde"] }

async-trait = "0.1"
error-stack = { workspace = true }

[features]
interfaces = []
prelude = []
default = ["prelude", "interfaces"]
uuid = []
time = []
