[package]
name = "driver"
version.workspace = true
edition.workspace = true
authors.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenvy = "0.15.7"
deadpool-redis = "0.12.0"
sqlx = { version = "0.7", features = ["uuid", "time", "postgres", "runtime-tokio-native-tls"] }
serde_json = "1"
async-trait = "0.1"
anyhow = { workspace = true }
thiserror = { workspace = true }

kernel = { path = "../kernel" }
