name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    uses: ShuttlePub/workflows/.github/workflows/check.yml@a95cf7631a550a66628dd4a2a8d6ef4d253edab4
    with:
      workspace: '[ "kernel", "application", "server" ]'
  check-driver:
    uses: ShuttlePub/workflows/.github/workflows/test-psql.yml@454354614b775cd3b470c991b532e8db1c1ed89f
    with:
      workspace: driver
  coverage:
    uses: ShuttlePub/workflows/.github/workflows/coverage.yml@main
    secrets: inherit
